config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'
  namespace :admin do
    resources :employees
  end

  root to: 'users#index'
  resources :users
  resources :contents
  resources :ctalogs

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord

end

app/models/employee.rb
class Employee < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :employee_id, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :contents
  validates :name, :telephonenumber, presence: true
  validates :name, length: { maximum: 30 }
end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < ApplicationController
  before_action :require_admin

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to admin_employee_url(@employee), notice: "ユーザー: #{@employee.name}を登録しました"
    else
      render :new
    end
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def index
    @employee = Employee.all
  end

  def update
    @employee = Employee.find(params[:id])

    if @employee.update(employee_params)
      redirect_to admin_employee_url(@employee), notice: "#{@employee.nemw}を登録しました"
    else
      render :edit
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    redirect_to admin_employee_url, notice: "ユーザー#{@employee.name}を削除しました。"
  end

  private

  def employee_params
    params.require(:employee).permit(:name, :employee_id, :admin, :password, :password_confirmation)
  end

  def require_admin
    redirect_to root_url unless current_employee.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :abc, :current_employee, :current_employee_name, :emp_name, :abc123
  before_action :login_required


  private

  def current_user
    @current_user = session[:user_id]
  end

  def abc
    @abc = session[:user_name]
  end

  def abc123
    @abc123 = session[:nameabc]
  end

  def current_employee
    @current_employee ||= Employee.find_by(id: session[:employee_num]) if session[:employee_num]
  end

  def current_employee_name
    @current_employee_name = session[:employee_name]
  end

  def emp_name
    @emp_name =   session[:emp_name]
  end

  def login_required
    redirect_to login_url unless current_employee
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

  def index
    @content = Content.where(user_id: abc)
    @user = User.find(current_user)
  end

  def show
    @content = Content.where(user_id: current_user)
    @user = User.find(current_user)
  end

  def new
    @content = Content.new
    @user = User.find(current_user)
  end

  def create
    @user = User.find(current_user)
    content = Content.new(content_params.merge(
    user_id: @user.name).merge(reactor: emp_name))
    content.save!
    redirect_to contents_url, notice: " 内容を登録しました"
  end

  def edit
    @content = Content.find(params[:id])
  end

  def update
    content = Content.find(params[:id])
    content.update!(content_params.merge(
    user_id: create_user).merge(reactor: emp_name))
    redirect_to contents_url, notice: "内容を更新しました。"
  end

  def destroy
    content = Content.find(params[:id])
    content.destroy
    redirect_to contents_url, notice: "内容を削除しました。"
  end

  private

  def content_params
    params.require(:content).permit(:content, :datetime,)
  end
end

app/controllers/ctalogs_controller.rb
class CtalogsController < ApplicationController
  def index
    @content = Content.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

  def new
  end

  def create
    employee = Employee.find_by(employee_id: session_params[:employee_id])

    if employee&.authenticate(session_params[:password])
      session[:employee_num] = employee.id
      session[:employee_name] = employee.name
      redirect_to root_url, notice: "#{employee.name}ログインしました。"
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_url, notice: 'ログアウトしました'
  end

  private

  def session_params
    params.require(:session).permit(:employee_id, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
    session[:emp_name] = current_employee_name
  end

  def show
    @user = User.find(params[:id])
    session[:user_id] = @user.id
    session[:user_name] = @user.name
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
    redirect_to users_url, notice: "#{@user.name}様を登録しました"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update!(user_params)
    redirect_to user_url, notice: "#{user.name}様を更新しました。"
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_url, notice: "#{user.name}様を削除しました。"
  end

  private

  def user_params
    params.require(:user).permit(:name, :telephonenumber, :birthday, :gender, :address)
  end
end

app/helpers/admin/employees_helper.rb
module Admin::EmployeesHelper
end

app/helpers/admin/login_users_helper.rb
module Admin::LoginUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/ctalog_helper.rb
module CtalogHelper
end

app/helpers/ctalogs_helper.rb
module CtalogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/employees/_form.html.slim
= form_with model: [:admin, @employee], local: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :employee_id
    = f.text_field :employee_id, class: 'form-control'
  .form-check
    = f.label :admin, class: 'form-check-label' do
      = f.check_box :admin, class: 'form-check-input'
      | 管理者権限
  br
  .form-group
    = f.label :password
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation
    = f.password_field :password_confirmation, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-primary'

app/views/admin/employees/edit.html.slim
h1 ユーザーの編集
.nav.justify-content-end
  = link_to '戻る', admin_employees_path, class: 'nav-link'


= render partial: 'form', locals: { employee: @employee }

app/views/admin/employees/index.html.slim
h1 ユーザー一覧

= link_to '新規登録', new_admin_employee_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= Employee.human_attribute_name(:name)
      th= Employee.human_attribute_name(:employee_id)
      th= Employee.human_attribute_name(:admin)
      th= Employee.human_attribute_name(:created_at)
      th= Employee.human_attribute_name(:updated_at)
      th
    tbody
    - @employee.each do |emp|
      tr
        td= link_to emp.name, [:admin, emp]
        td= emp.employee_id
        td= emp.admin? ? 'あり' : 'なし'
        td= emp.created_at.strftime("%Y年 %m月 %d日")
        td= emp.updated_at.strftime("%Y年 %m月 %d日")
        td
          = link_to '編集', edit_admin_employee_path(emp), class: 'btn btn-primary mr-3'
          = link_to '削除', [:admin, emp], method: :delete, data: { confirm: "履歴を削除します。よろしいですか？"}, class: 'btn btn-danger'

app/views/admin/employees/new.html.slim
h1 ユーザー登録

.nav.justify-content-end
  = link_to '一覧', admin_employees_path, class: 'nav-link'


= render partial: 'form', locals: { employee: @employee }

app/views/admin/employees/show.html.slim
h1 ユーザーの詳細

.nav.justify-content-end
  = link_to '一覧', admin_employees_path, class: 'nav-link'

table.table.table-hover
  tbody
    tr
      th= Employee.human_attribute_name("ユーザー番号")
      td= @employee.id
    tr
      th= Employee.human_attribute_name(:name)
      td= @employee.name
    tr
      th= Employee.human_attribute_name(:employee_id)
      td= @employee.employee_id
    tr
      th= Employee.human_attribute_name(:admin)
      td= @employee.admin? ? 'あり' : 'なし'
    tr
      th= Employee.human_attribute_name(:created_at)
      td= @employee.created_at.strftime("%Y年 %m月 %d日")
    tr
      th= Employee.human_attribute_name(:updated_at)
      td= @employee.updated_at.strftime("%Y年 %m月 %d日")
= link_to '編集', edit_admin_employee_path, class: 'btn btn-primary mr-3'
= link_to '削除', [:admin, @employee], method: :delete, data: { confirm: "#{@employee.name}を削除します。よろしいですか？"}, class: 'btn btn-danger'

app/views/contents/_form.html.slim
= form_with model: @content, local: true do |f|
  br
  .form-inline
    = f.label :datetime
    = ( f.date_select :datetime, discard_year: true, use_month_numbers: true, class: 'form-control', id: 'content_datetime', date_separator: '月' ) + '日'
  br
  .form-group
    = f.label :content
    = f.text_field :content, style: "width:500px;",  class: 'form-control', id: 'content_content', value: '訪問'
  = f.submit '内容作成', class: 'btn btn-primary'

app/views/contents/edit.html.slim
h1 履歴編集

.nav.justify-content-end
  = link_to '履歴一覧に戻る', contents_path, class: 'nav-link'

= render partial: 'form', locals: { content: @content }

app/views/contents/index.html.slim
h1 #{@user.name}様の内容一覧

.nav.justify-content-end
  = link_to '顧客登録・一覧へ', users_path, class: 'nav-link'

= link_to '内容作成', new_content_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= Content.human_attribute_name(:id)
      th= Content.human_attribute_name(:content)
      th= Content.human_attribute_name(:datetime)
      th= Content.human_attribute_name(:reactor)
      th
  tbody
    - @content.each do |content|
      tr
        td= content.id
        td= content.content
        td= content.datetime.strftime("%Y年 %m月 %d日 %A")
        td= content.reactor
        td
          = link_to '編集', edit_content_path(content),class: 'btn btn-primary mr-3'
          = link_to '削除', content, method: :delete, data: { confirm: "履歴を削除します。よろしいですか？"}, class: 'btn btn-danger'

app/views/contents/new.html.slim
h1 #{@user.name}様の内容登録

.nav.justify-content-end
  = link_to '戻る', contents_path, class: 'nav-link'

= render partial: 'form', locals: { content: @content }

app/views/ctalogs/index.html.slim
h1 全内容一覧


.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= "顧客名"
      th= Content.human_attribute_name(:content)
      th= Content.human_attribute_name(:datetime)
      th= Content.human_attribute_name(:reactor)
      th
  tbody
    - @content.each do |content|
      tr
        td= content.user_id
        td= content.content.to_s[0..10]
        td= content.datetime.strftime("%Y年 %m月 %d日 %A")
        td= content.reactor

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Sample
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
  .app-title.navbar.navbar-expand-md.navbar-light.bg-light
    .navbar-brand Sample

    ul.navbar-nav.ml-auto
      - if current_employee
        li.nav-item= link_to '顧客一覧', users_path, class: 'nav-link'
        li.nav-item= link_to '内容', ctalogs_path, class: 'nav-link'
        - if current_employee.admin?
          li.nav-item= link_to 'ユーザー一覧', admin_employees_path, class: 'nav-link'
        li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
      - else
        li.nav-item= link_to 'ログイン', login_path, class: 'nav-link'
  .container
    - if flash.notice.present?
      .alert.alert-success= flash.notice
    = yield

app/views/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation
    - user.errors.full_messages.each do |messeage|
      li= messeage


= form_with model: user, local: true do |f|
  .form-inline
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'user_name', placeholder: '名前'
  br
  .form-inline
    = f.label :birthday
    = ( f.date_select :birthday, discard_year: true, use_month_numbers: true, class: 'form-control', id: 'user_birthday', date_separator: '月' ) + '日'
  br
  .form-group
    = f.label :gender ,:男
    = f.radio_button :gender, '男性'
    = f.label :gender, :女
    = f.radio_button :gender, '女性'
  .form-inline
    = f.label :address
    = f.text_field :address, style: "width:500px;",  class: 'form-control', id: 'user_address', value: '雲南市'
  br
  .form-inline
    = f.label :telephonenumber
    = f.text_field :telephonenumber, class: 'form-control', id: 'user_telephonenumber', value: '0854'
  br
  = f.submit nil, class: 'btn btn-primary'

app/views/users/edit.html.slim
h1 #{@user.name}様の情報変更

.nav.justify-content-end
  = link_to 'ホーム画面に戻る', users_path, class: 'nav-link'

= render partial: 'form', locals: { user: @user }

app/views/users/index.html.slim
h1 顧客登録・一覧

= link_to '顧客登録', new_user_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= User.human_attribute_name(:id)
      th= User.human_attribute_name(:name)
      th= User.human_attribute_name(:telephonenumber)
      th= User.human_attribute_name(:birthday)
      th= User.human_attribute_name(:gender)
      th= User.human_attribute_name(:address)
      th
  tbody
    - @user.each do |user|
      tr
        td= user.id
        td= link_to user.name, user
        td= user.telephonenumber
        td= user.birthday.strftime("%m月 %d日")
        td= user.gender
        td= user.address
        td
          = link_to '編集', edit_user_path(user),class: 'btn btn-primary mr-3'
          = link_to '削除', user, method: :delete, data: { confirm: "#{user.name}を削除します。よろしいですか？"}, class: 'btn btn-danger'

app/views/users/new.html.slim
h1 新規顧客登録画面

.nav.justify-content-end
  = link_to '戻る', users_path, class: 'nav-link'


= render partial: 'form', locals: { user: @user }

app/views/users/show.html.slim
h1 #{@user.name}様の詳細

= link_to '内容', contents_url(num:@user.id), class: 'btn btn-primary'

.nav.justify-content-end
  = link_to '戻る', users_path, class: 'nav-link'

table.table.table-hover
  tbody
    tr
      th= User.human_attribute_name(:id)
      td= @user.id
    tr
      th= User.human_attribute_name(:name)
      td= @user.name
    tr
      th= User.human_attribute_name(:telephonenumber)
      td= @user.telephonenumber
    tr
      th= User.human_attribute_name(:birthday)
      td= @user.birthday.strftime("%m月 %d日")
    tr
      th= User.human_attribute_name(:gender)
      td= @user.gender
    tr
      th= User.human_attribute_name(:address)
      td= @user.address
= link_to '編集', edit_user_path,class: 'btn btn-primary mr-3'
= link_to '削除', @user, method: :delete, data: { confirm: "#{@user.name}を削除します。よろしいですか？"}, class: 'btn btn-danger'